# Generated by Django 3.2.6 on 2021-11-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources_Module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
        migrations.AlterField(
            model_name='resource',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Resources_Module.hospital'),
        ),
    ]
