# Generated by Django 3.2.6 on 2021-11-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources_Module', '0002_auto_20211110_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default='Image', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
