# Generated by Django 3.2.6 on 2021-11-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources_Module', '0003_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(upload_to='hospital_images'),
        ),
    ]
