# Generated by Django 3.2.6 on 2021-11-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources_Module', '0004_alter_hospital_image'),
        ('Registration_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resources_Module.hospital'),
        ),
    ]
